from enum import Enum

class Orientacao(Enum):
	HORIZONTAL_ESQUERDA = 0
	HORIZONTAL_DIREITA = 1
	VERTICAL_CIMA = 2
	VERTICAL_BAIXO = 3
	DIAGONAL_PRINCIPAL_ESQUERDA = 4
	DIAGONAL_PRINCIPAL_DIREITA = 5
	DIAGONAL_SECUNDARIA_ESQUERDA = 6
	DIAGONAL_SECUNDARIA_DIREITA = 7